name: Monitoring NodeJS Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Show folders
        run: ls 
      - name: Install dependencies
        run: cd src
        run: npm install
      - name: Run Tests
        run: npm Test
      - name: start application
        run: npm start
      - name: Project Completed
        run: echo "You are doing a good job" 
          

    
